version: "3.7"

services:
  amp:
    build: .
    env_file: ".env"
    volumes:
      - ./src/:/var/www/html
      - ./dev/local/internal_build.sh:/home/build.sh
      - ./dev/local/apache2.conf:/etc/apache2/apache2.conf
    ports:
      - ${PORT_WEB}:80
      - ${PORT_DB}:3306
#      - ${REDIS_PORT}:6379
    restart: always
  