version: "3.7"

services:
  amp:
    build: .
    volumes:
      - ./src/:/var/www/html
      - ./scripts/internal:/home
    ports:
      - ${PORT_WEB}:80
      - ${PORT_DB}:3306
    restart: always
  